-- Movies INSERT statements
-- Generated at: 2025-11-16T04:15:53+04:00

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 301, 'Матрица', 'Жизнь Томаса Андерсона разделена на две части: днём он — самый обычный офисный работник, получающий нагоняи от начальства, а ночью превращается в хакера по имени Нео, и нет места в сети, куда он бы не смог проникнуть. Но однажды всё меняется. Томас узнаёт ужасающую правду о реальности.', 'Лана Вачовски,Лилли Вачовски', 1999, 'США,Австралия', 'фантастика,боевик', 'https://www.kinopoisk.ru/film/301/', 136, 8.7, 0.0, 'WATCHED', 1, NULL, NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 348, 'Эта замечательная жизнь', 'Джордж Бейли, владелец кредитной компании в выдуманном американском городке Бедфорд Фоллс, честный, отзывчивый, любящий муж и отец, подавлен свалившимися на него невзгодами и подумывает о самоубийстве.

Очевидно, что человек, отказывающийся от самого большого дара Бога – жизни – нуждается в помощи ангела-хранителя. И Небеса отправляют ему на выручку Кларенса, единственного свободного на тот момент Ангела Второго Класса, приятного, доброго, но неопытного, еще даже не заслужившего крылья.

Если он сделает свою работу хорошо и сможет отговорить Джорджа от смертного греха, он получит крылья. А времени у него почти не осталось… Кларенс находит единственно правильное решение – показать Джорджу мир, в котором тот не существует.', 'Фрэнк Капра', 1947, 'США', 'фэнтези,драма,мелодрама,семейный', 'https://www.kinopoisk.ru/film/348/', 130, 8.6, 0.0, 'WATCHED', 1, '2021-12-15 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 388, 'Расёмон', 'Древняя Япония. В лесу изнасилована женщина, а её муж убит. Есть четыре точки зрения на это происшествие, у каждого из четырех свидетелей — своя. Каждая сторона проливает свет на случившееся, добавляя дополнительные детали.', 'Акира Куросава', 1950, 'Япония', 'драма,криминал', 'https://www.kinopoisk.ru/film/388/', 88, 8.2, 0.0, 'WATCHED', 1, '2022-11-09 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 413, 'Беги, Лола, беги', 'Лола и Манни живут в Берлине и безумно любят друг друга. И когда Манни — маленький курьер большого бандита — теряет сумку с деньгами своего босса, спасти его может только Лола. Но чтобы раздобыть совсем не маленькую сумму в сто тысяч марок, у девушки есть только 20 минут. Каждая секунда может означать разницу между жизнью и смертью.', 'Том Тыквер', 1998, 'Германия', 'боевик,триллер,криминал', 'https://www.kinopoisk.ru/film/413/', 81, 7.7, 0.0, 'WATCHED', 1, '2023-05-24 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 604, 'Королевская битва', 'Королевская битва — санкционированная правительством жестокая игра, в которой школьников заставляют участвовать под угрозой уничтожения. На необитаемом острове 42 старшеклассника на протяжении трёх дней будут безжалостно убивать друг друга с помощью случайных предметов и смекалки. Живым с острова вернётся только один.', 'Киндзи Фукасаку', 2000, 'Япония', 'боевик,триллер,фантастика,драма', 'https://www.kinopoisk.ru/film/604/', 114, 7.5, 0.0, 'WATCHED', 1, '2022-11-02 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 664, 'Семьянин', 'Судьба в облике чернокожего Санты ставит перед Джеком непростой выбор. Он может быть президентом инвестиционной компании, жить в роскошной квартире, раскатывать на последней модели «Феррари» и при этом оставаться холостяком. А может стать семьянином, но работать продавцом автопокрышек, покупать одежду в супермаркете и ездить на минивэне.', 'Бретт Рэтнер', 2000, 'США', 'фэнтези,драма,мелодрама,комедия', 'https://www.kinopoisk.ru/film/664/', 125, 6.8, 0.0, 'WATCHED', 1, '2021-12-01 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 678, 'Банды Нью-Йорка', 'Нью-Йорк, 1863 год. В диких трущобах города американской мечты действует только один закон - закон силы. Здесь идет в ход любое оружие, никто не считает потерь и не оплакивает погибших. В одной из жестоких стычек от рук вожака коренных американцев - Мясника Билла погибает предводитель банды ирландцев Вэллон.

Его сын Амстердам надолго попадает в исправительную школу, затаив ненависть на Мясника, ставшего хозяином окрестных кварталов. Спустя годы не узнанный никем Амстердам возвратится на родные улицы с единственной целью - отомстить убийце отца.', 'Мартин Скорсезе', 2002, 'США,Германия,Великобритания,Нидерланды,Италия', 'драма,криминал', 'https://www.kinopoisk.ru/film/678/', 167, 7.5, 0.0, 'WATCHED', 1, '2023-06-21 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 747, 'Малена', 'Малена - красавица-вдова, наваждение мужчин и предмет зависти женщин. Жены распускают о ней грязные сплетни. Мужья преследуют ее по пятам и грезят о ней.

«Мне было 13, когда я увидел ее впервые. Прошло время, я любил многих женщин, и когда мы были близки, они спрашивали: буду ли я помнить их? И я говорил: да, я буду помнить вас. Но единственная, кого я никогда не забуду - та, которая никогда не спрашивала. Малена».', 'Джузеппе Торнаторе', 2000, 'Италия,США', 'драма,мелодрама,военный', 'https://www.kinopoisk.ru/film/747/', 100, 7.4, 0.0, 'WATCHED', 1, '2023-01-11 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 821, 'Интуиция', 'В один суматошный зимний день в нью-йоркской толпе Джонатан встретил Сару. Два незнакомых человека в объятом рождественской лихорадкой городе обнаруживают, что их неодолимо тянет друг к другу. И они решают проверить судьбу: он пишет свой телефон на банкноте, она — в книге. Купюру разменивают, а книгу сдают букинисту. Джонатан и Сара уверены, что скоро увидятся вновь.', 'Питер Челсом', 2001, 'США', 'мелодрама,комедия', 'https://www.kinopoisk.ru/film/821/', 87, 6.8, 0.0, 'WATCHED', 1, '2022-12-28 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 1846, 'Небесный замок Лапута', 'Альтернативная реальность, соответствующая началу XX века. В руках девочки по имени Сита находится Летающий Камень. За ним охотятся агенты правительства и пираты, потому что Камень представляет огромную ценность. Пытаясь скрыться от преследователей, Сита встречает Падзу, своего ровесника, работающего в шахтерском городке. Вместе дети выясняют, что Камень — ключ к таинственному летающему острову Лапута.', 'Хаяо Миядзаки', 1986, 'Япония', 'аниме,мультфильм,фэнтези,приключения,семейный', 'https://www.kinopoisk.ru/film/1846/', 125, 8.0, 0.0, 'WATCHED', 1, '2022-11-23 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 5264, 'Рассекая волны', 'Бог дает каждому что-то, чтобы он стал лучше. Молодая девушка Бесс из отдаленной общины на северо-западе Шотландии влюбилась в хорошего парня - Яна, работающего на буровой установке в море. Несмотря на противостояние родственников, они женятся. Бесс просит Бога, чтобы Ян всегда был рядом с ней, и Ян возвращается к ней искалеченным после несчастного случая на буровой. Что может сделать молодая женщина, чтобы ее любимый остался жив? На какую жертву может пойти?', 'Ларс фон Триер', 1996, 'Дания,Швеция,Франция,Нидерланды,Норвегия,Исландия,Испания', 'драма', 'https://www.kinopoisk.ru/film/5264/', 159, 7.8, 0.0, 'WATCHED', 1, '2022-10-05 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 6144, 'Реальная любовь', 'Любовь поистине правит всеми вокруг — от премьер-министра, влюбившегося в сотрудницу своего аппарата, до писателя, сбежавшего на юг Франции, чтобы склеить свое разбитое сердце.', 'Ричард Кёртис', 2003, 'Великобритания,Франция,США', 'мелодрама,комедия,драма', 'https://www.kinopoisk.ru/film/6144/', 129, 7.6, 0.0, 'WATCHED', 1, '2022-12-21 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 8126, 'Крокодил Данди', 'Американская журналистка приезжает в глубинку Австралии, и охотник на крокодилов знакомит ее с местными достопримечательностями. Она же приглашает его в Нью-Йорк, и там отважный охотник попадает в неведомые ему джунгли...', 'Питер Фэймен', 1986, 'Австралия', 'боевик,комедия,приключения', 'https://www.kinopoisk.ru/film/8126/', 97, 6.6, 0.0, 'WATCHED', 1, '2022-12-07 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 9617, 'Крупная рыба', 'В основу этой приключенческой ленты положен роман Дэниела Уоллеса «Большая рыба: роман мифических пропорций». Умирает отец, о жизни которого сын хочет узнать как можно больше, собирая истории о нем.

Сын пытается воссоздать ускользающую жизнь отца в серии легенд и мифов, которые тот придумывает на основе разрозненных фактов. Взлеты и падения в жизни человека в итоге предстают в неожиданном ракурсе.', 'Тим Бёртон', 2003, 'США', 'фэнтези,драма,мелодрама,приключения', 'https://www.kinopoisk.ru/film/9617/', 125, 8.0, 0.0, 'WATCHED', 1, '2022-03-30 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 40804, 'Ты у меня одна', 'Бывший боксер, а ныне - рядовой инженер, Евгений Тимошин получает возможность изменить свою жизнь к лучшему. Его зовет с собой в Америку молодая, красивая, богатая женщина, которая с детства в него влюблена. Но Тимошин любит свою жену, и никогда не мечтал об Америке...', 'Дмитрий Астрахан', 1993, 'Россия', 'драма', 'https://www.kinopoisk.ru/film/40804/', 101, 7.1, 0.0, 'WATCHED', 1, '2022-01-26 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 42610, 'Интердевочка', 'Валютная проститутка мечтает вырваться из замкнутого круга — выйти замуж за иностранца, уехать за границу и стать респектабельной дамой.', 'Пётр Тодоровский', 1989, 'СССР,Швеция', 'драма', 'https://www.kinopoisk.ru/film/42610/', 151, 7.0, 0.0, 'WATCHED', 1, '2023-03-15 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 43817, 'Сказка странствий', 'Два злодея похищают мальчика-сироту, обладающего волшебным даром находить золото. Его сестра долгие годы ищет его, испытывая лишения, и наконец встречается с братом. Но оказывается, что найти — еще не значит спасти.', 'Александр Митта', 1983, 'СССР,Чехословакия,Румыния', 'фэнтези,приключения', 'https://www.kinopoisk.ru/film/43817/', 101, 7.8, 0.0, 'WATCHED', 1, '2022-01-12 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 43911, 'Солярис', 'На космическую станцию, сотрудники которой давно и тщетно пытаются сладить с загадкой планеты Солярис, полностью покрытой Океаном, прибывает новый учёный, психолог Крис Кельвин. Его задача - разобраться в странных сообщениях, поступающих со станции и закрыть её вместе со всей бесплодной «соляристикой». Поначалу ему кажется, что немногие уцелевшие на станции ученые сошли с ума, а потом он и сам становится жертвой жуткого наваждения: ему является его жена Хари, некоторое время назад покончившая с собой.', 'Андрей Тарковский', 1972, 'СССР', 'фантастика,драма,детектив', 'https://www.kinopoisk.ru/film/43911/', 169, 8.0, 0.0, 'WATCHED', 1, '2023-03-22 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 47814, 'Весна, лето, осень, зима... и снова весна', 'Никому не дано нарушить смену времен года, когда вначале все рождается, затем растет, а потом угасает. Ход жизни неподвластен и двум монахам, живущим в плавучей хижине на горном озере.

По мере наступления времени года их души наполняются энергией, что ведет как к чувству одухотворенности, так и к трагедии. Они не могут вырваться из круга жизни, желаний, страданий и страстей, которым подвержены все из нас.', 'Ким Ки Дук', 2003, 'Корея Южная,Германия', 'драма', 'https://www.kinopoisk.ru/film/47814/', 103, 8.0, 0.0, 'WATCHED', 1, '2022-09-14 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 49166, 'Коралина в Стране Кошмаров', 'Коралина, маленькая девочка, попадает в другой мир, скрытый за секретной дверцей. Этот мир — ее альтернативная жизнь, которая не перестает ее радовать, все здесь хорошо, но только до поры до времени. Однажды она понимает, что ее настоящим родителям за ее проделки угрожает смертельная опасность. Коралине придется найти выход из мира, наполненного призраками, в реальную жизнь…', 'Генри Селик', 2008, 'США', 'мультфильм,фэнтези,триллер,драма,семейный', 'https://www.kinopoisk.ru/film/49166/', 100, 7.7, 0.0, 'WATCHED', 1, NULL, NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 63912, 'Укрощение строптивого', 'Категорически не приемлющий женского общества грубоватый фермер вполне счастлив и доволен своей холостяцкой жизнью. Но неожиданно появившаяся в его жизни женщина пытается изменить его взгляды на жизнь и очаровать его.', 'Франко Кастеллано,Джузеппе Моччиа', 1980, 'Италия', 'мелодрама,комедия', 'https://www.kinopoisk.ru/film/63912/', 107, 7.6, 0.0, 'WATCHED', 1, '2023-01-25 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 75871, 'Олдбой', '1988 год. Обыкновенный и ничем непримечательный бизнесмен О Дэ-cу в день трёхлетия дочери по пути домой напивается, начинает хулиганить и закономерно попадает в полицейский участок. Из участка его под своё поручительство забирает друг детства. Пока тот звонит жене незадачливого пьяницы, О Дэ-су пропадает. Неизвестные похищают его и помещают в комнату без окон на 15 лет.', 'Пак Чхан-ук', 2003, 'Корея Южная', 'триллер,детектив,драма,криминал', 'https://www.kinopoisk.ru/film/75871/', 120, 8.4, 0.0, 'WATCHED', 1, '2023-09-13 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 77531, 'Тренер Картер', 'Фильм основан на реальной истории, происшедшей в 1999 году в Ричмонде, штат Калифорния. Тренер школьной команды по баскетболу Кен Картер принял в середине сезона беспрецедентное решение, запретив игрокам, не испытавшим еще ни одного поражения, выходить на площадку из-за низкой успеваемости в школе. В итоге команда пропустила две игры в чемпионате, а юным баскетболистам был закрыт доступ в спортзал до тех пор, пока они не стали хорошо учиться. Поступок Картера вызвал одновременно и одобрение, и резкую критику со стороны родителей игроков и школьного руководства. Среди членов команды был и сын тренера, поступивший впоследствии в престижное учебное заведение.', 'Томас Картер', 2005, 'США,Германия', 'биография,спорт,драма', 'https://www.kinopoisk.ru/film/77531/', 136, 7.3, 0.0, 'WATCHED', 1, '2022-04-06 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 78378, 'Парфюмер: История одного убийцы', 'Жестокий, никогда не знавший любви, сирота Жан-Батист Гренуй настоящих успехов достиг лишь на одном поприще – среди парфюмеров ему никогда не было равных. По его духам сходит с ума весь высший свет, не подозревая о том, какой страшной ценой будет получен последний, идеальный аромат.', 'Том Тыквер', 2006, 'Германия,Франция,Испания,США', 'фэнтези,драма,криминал', 'https://www.kinopoisk.ru/film/78378/', 147, 7.5, 0.0, 'WATCHED', 1, '2023-05-17 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 160929, 'Ангел-А', '28-летний Андре должен десятки тысяч евро различным бандитам по всему Парижу. Когда подходит срок расплаты, он понимает, что шансов расплатиться - нет. И в полиции, и в американском посольстве ему отказывают в помощи.

Но вот, решив покончить с собой, он видит на мосту сногсшибательную красотку в очень маленьком черном платье, которая прыгает в Сену. Андре бросается за ней. Спасенная девушка обещает помочь Андре во всем: она придумывает удивительные способы добывать деньги и помогает решить проблемы с кредиторами. Но тут Андре начинает задаваться вопросом – почему эта восхитительная девушка так старается ради него?', 'Люк Бессон', 2005, 'Франция', 'фэнтези,драма,мелодрама,комедия', 'https://www.kinopoisk.ru/film/160929/', 91, 7.0, 0.0, 'WATCHED', 1, '2023-01-04 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 232684, 'Десять лодок', 'Далекое прошлое, целые века до прихода в Австралию белого человека. Дэйинди домогается жены старшего брата, и чтобы наставить его на истинный путь, ему рассказывают  старинную историю о любви, вражде, колдовстве и мести... ', 'Рольф Де Хер,Питер Джигирр', 2006, 'Австралия', 'драма,комедия,приключения', 'https://www.kinopoisk.ru/film/232684/', 90, 6.9, 0.0, 'WATCHED', 1, '2022-12-14 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 232785, 'Господин Никто', 'Проснувшийся немощным стариком Немо Никто оказывается последним смертным в гротескном будущем. Все люди уже давно бессмертны и с удовольствием наблюдают за телешоу, где главная звезда — дряхлый и безумный старик Немо, доживающий последние дни. К нему приходит журналист, и Немо рассказывает ему свою историю.', 'Жако ван Дормель', 2009, 'Бельгия,Германия,Канада,Франция,Великобритания,Люксембург,США', 'фантастика,мелодрама,фэнтези,драма', 'https://www.kinopoisk.ru/film/232785/', 138, 7.7, 0.0, 'WATCHED', 1, '2022-07-27 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 259788, 'Неуместный человек', 'Сорокалетний Андреас при загадочных обстоятельствах попадает в странный город — абсолютная идиллия, опрятные улицы, благополучные жители. Его принимают на работу в офис большой компании — сотрудники благожелательны, условия работы безупречны. Андреас даже заводит себе жену и пытается наладить семейный быт.

Но Андреасу не по себе. Что-то не так. Люди вокруг лишены эмоций, существуют, как роботы, по какому-то заведенному порядку, но жизнью это назвать нельзя. Во время прогулки Андреас вдруг видит нанизанный на железные прутья ограды труп своего коллеги, выбросившегося из окна офиса. Что послужило причиной самоубийства?..', 'Йенс Лиен', 2006, 'Норвегия,Исландия', 'фантастика,фэнтези,драма,комедия,детектив', 'https://www.kinopoisk.ru/film/259788/', 95, 7.2, 0.0, 'WATCHED', 1, '2022-10-12 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 272410, 'На краю рая', 'Германия и Турция. Рассказ о судьбах шести человек, находящихся в поисках прощения и примирения. Пенсионер и вдовец Али спасается от одиночества в гамбургских борделях, пока именно там он не встречает Йетар. За те же деньги, что она зарабатывает в борделе, он приглашает её жить с ним. Неджат, образованный сын Али, преподающий германистику в гамбургском университете очень удивлён странным выбором своего упрямого отца. Только когда он узнаёт, что Йетар посылает большую часть денег своей дочери Айтан в Стамбул, чтобы профинансировать её учёбу, он начинает уважать её. Когда Йетар трагически погибает, Неджат отправляется на поиски Айтан. Но будучи политической активисткой, та уже давно сбежала из Турции и нашла приют у Лотты и её матери Сюзанны в Германии... Понадобится не одно путешествие, чтобы герои нашли друг друга... хоть и неожиданным образом.', 'Фатих Акин', 2007, 'Германия,Турция,Италия', 'драма', 'https://www.kinopoisk.ru/film/272410/', 122, 7.7, 0.0, 'WATCHED', 1, '2023-04-15 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 316376, 'На Западном фронте без перемен', 'Германская империя, 1917 год. Преисполненные патриотизмом 19-летний Пауль Боймер и его друзья-одноклассники отправляются добровольцами на фронт, где им предстоит испытать на себе ужасы Первой мировой войны.', 'Эдвард Бергер', 2022, 'Германия,США,Великобритания', 'военный,боевик,драма,история', 'https://www.kinopoisk.ru/film/316376/', 148, 7.8, 0.0, 'WATCHED', 1, '2023-02-08 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 408410, 'Гран Торино', 'Вышедший на пенсию автомеханик Уолт Ковальски проводит дни, починяя что-то по дому, попивая пиво и раз в месяц заходя к парикмахеру. И хотя последним желанием его недавно почившей жены было совершение им исповеди, Уолту – ожесточившемуся ветерану Корейской войны, всегда держащему свою винтовку наготове, – признаваться в общем-то не в чем. Да и нет того, кому он доверял бы в той полной мере, в какой доверяет своей собаке Дейзи.

Все те люди, коих он некогда называл своими соседями, либо переехали, либо ушли в мир иной, а на смену им пришли иммигранты, которых он откровенно презирает. Противясь буквально всему, во что упирается его взгляд, – покосившиеся карнизы, заросшие лужайки домов и лица иностранцев повсюду; бесцельно шатающиеся шайки подростков, состоящие из хмонгов, латиносов и афро-американцев, полагающих, что окрестный мир целиком принадлежит им одним; неоперившиеся чужаки, в которых оказалось превратились собственные дети и внуки, – Уолт просто неспешно проживает остаток своей жизни.

До той самой ночи, когда кто-то попытается украсть его «Гран Торино»...', 'Клинт Иствуд', 2008, 'США,Германия', 'драма', 'https://www.kinopoisk.ru/film/408410/', 116, 8.1, 0.0, 'WATCHED', 1, '2022-08-17 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 423210, 'Три идиота', 'Двое друзей отправляются на поиски пропавшего приятеля. В этом путешествии им предстоит постоянно ввязываться в уже давно забытые споры, расстроить чужую свадьбу и побывать на похоронах. Они вспоминают своего приятеля, неудержимого и свободомыслящего Ранчо, который каким-то удивительным образом ворвался в их жизнь и всё в ней изменил.', 'Раджкумар Хирани', 2009, 'Индия', 'комедия,мелодрама', 'https://www.kinopoisk.ru/film/423210/', 170, 8.4, 0.0, 'WATCHED', 1, '2022-08-31 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 462247, 'Хранитель времени', 'После того, как ловкому и изобретательному Хьюго удается раскрыть секрет таинственного механизма, оставленного его погибшим отцом, он отправляется в путешествие, которое изменит тех, кто его окружает, и приведет в безопасное и прекрасное место, которое он назовет своим домом.', 'Мартин Скорсезе', 2011, 'США,Великобритания,Франция', 'драма,детектив,приключения,семейный', 'https://www.kinopoisk.ru/film/462247/', 126, 7.5, 0.0, 'WATCHED', 1, '2023-07-01 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 462305, 'Ирландец', 'В доме престарелых сильно пожилой мужчина по имени Фрэнк Ширан вспоминает свою жизнь. В 1950-е он работал простым водителем грузовика, совсем не хотел быть гангстером и думал, что маляры — это те, кто красят дома, когда случайно познакомился с криминальным авторитетом Расселом Буфалино. Тот взял парня под своё крыло, начал давать ему небольшие поручения, и вот уже Фрэнк по прозвищу Ирландец сам работает «маляром», мафиозным киллером. Вскоре Рассел сводит его с известным профсоюзным лидером Джимми Хоффой.', 'Мартин Скорсезе', 2019, 'США', 'криминал,драма,биография', 'https://www.kinopoisk.ru/film/462305/', 209, 7.8, 0.0, 'WATCHED', 1, '2023-06-21 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 464484, 'Облачный атлас', 'Шесть историй — пять реинкарнаций, происходящих в разное время, тесно переплетающихся между собой.', 'Лана Вачовски,Том Тыквер,Лилли Вачовски', 2012, 'США,Германия,Гонконг,Сингапур', 'фантастика,драма,боевик,детектив,приключения', 'https://www.kinopoisk.ru/film/464484/', 172, 7.4, 0.0, 'WATCHED', 1, '2022-08-10 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 464561, 'Цветы войны', '1937 год, Японо-китайская война. Американский гробовщик Джон направляется в Католическую церковь в Нанкине, чтобы подготовить священника к похоронам. По прибытии он оказывается в эпицентре военных действий и единственным мужчиной среди учениц монастыря и проституток из соседнего борделя. Джон решает выдать себя за священника и попытаться спасти обе группы от японской армии.', 'Чжан Имоу', 2011, 'Китай,Гонконг', 'военный,боевик,драма,история', 'https://www.kinopoisk.ru/film/464561/', 146, 7.5, 0.0, 'WATCHED', 1, '2022-05-04 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 470553, 'Прислуга', 'Американский Юг, на дворе 1960-е годы. Скитер только-только закончила университет и возвращается домой, в сонный городок Джексон, где никогда ничего не происходит. Она мечтает стать писательницей, вырваться в большой мир. Но для приличной девушки с Юга не пристало тешиться столь глупыми иллюзиями, приличной девушке следует выйти замуж и хлопотать по дому.

Мудрая Эйбилин на тридцать лет старше Скитер, она прислуживает в домах белых всю свою жизнь, вынянчила семнадцать детей и давно уже ничего не ждет от жизни, ибо сердце ее разбито после смерти единственного сына.

Минни - самая лучшая стряпуха во всем Джексоне, а еще она самая дерзкая служанка в городе. И острый язык не раз уже сослужил ей плохую службу. На одном месте Минни никогда подолгу не задерживается. Но с Минни лучше не связываться даже самым высокомерным белым дамочкам. Двух черных служанок и белую неопытную девушку объединяет одно - обостренное чувство справедливости и желание хоть как-то изменить порядок вещей. Смогут ли эти трое противостоять целому миру? Сумеют ли они выжить в этой борьбе?', 'Тейт Тейлор', 2011, 'США,Индия', 'драма', 'https://www.kinopoisk.ru/film/470553/', 146, 8.1, 0.0, 'WATCHED', 1, '2022-08-24 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 470769, 'Цветок пустыни', 'История Варис Дирие - простой девочки-кочевницы из Сомали. В 13 лет она сбежала из семьи, добралась до Могадишо, а потом оказалась в Лондоне. Через несколько лет ей удалось стать одной из популярнейших моделей мира.

Варис не была первой темнокожей топ-моделью, но она стала первой женщиной, которая публично осудила практику женского обрезания, была назначена специальным послом ООН и создала Фонд по борьбе с FGM.', 'Шерри Хорман', 2009, 'Великобритания,Германия,Австрия,Франция', 'драма,биография', 'https://www.kinopoisk.ru/film/470769/', 120, 7.3, 0.0, 'WATCHED', 1, '2022-07-20 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 478052, 'Барби', 'Самая обыкновенная стереотипная Барби живёт в великолепном розовом Барбиленде, и каждый её день идеален. Она меняет наряды, загорает на пляже, проводит время с другими Барби, день заканчивается шумной вечеринкой с танцами, и в этой позитивной кутерьме с блёстками влюблённый Кен — всего лишь приложение к Барби. Однажды куклу посещают мысли о смерти, и её сделанные под туфли с каблуками ноги вдруг становятся плоскими. Чтобы разобраться в происходящем и вернуть привычный пластмассовый мир, Барби придётся отправиться в мир реальный и найти там свою девочку-хозяйку. За ней увязывается не мыслящий жизни без своего кумира Кен.', 'Грета Гервиг', 2023, 'США,Великобритания', 'комедия,приключения,фэнтези', 'https://www.kinopoisk.ru/film/478052/', 114, 7.0, 0.0, 'WATCHED', 1, '2023-08-02 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 491724, 'Девушка с татуировкой дракона', '40 лет назад Харриет Вангер бесследно пропала на острове, принадлежащем могущественному клану Вангер. Тело так и не нашли, но её дядя убежден, что девушку убили, и что убийца является членом его собственной неблагополучной семьи. Он нанимает опального журналиста Микаэля Блумквиста и татуированную хакершу Лисбет Саландер для проведения расследования.', 'Дэвид Финчер', 2011, 'США,Швеция,Норвегия', 'детектив,триллер,драма,криминал', 'https://www.kinopoisk.ru/film/491724/', 158, 7.8, 0.0, 'WATCHED', 1, '2022-10-21 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 504465, 'Полночь в Париже', 'Писатель и безнадежный романтик, уверенный в том, что должен был жить в 1920-е годы, приезжает в Париж со своей возлюбленной на каникулы и попадает в прошлое. Встречаясь там с Хемингуэем, Пикассо, супругами Фицджеральдами, Гертрудой Стайн, он понимает, что принадлежит этому времени и хочет остаться там навсегда.', 'Вуди Аллен', 2011, 'США,Испания', 'фэнтези,мелодрама,комедия', 'https://www.kinopoisk.ru/film/504465/', 94, 7.6, 0.0, 'WATCHED', 1, '2023-09-20 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 572032, 'Топ Ган: Мэверик', 'Пит Митчелл по прозвищу Мэверик более 30 лет остается одним из лучших пилотов ВМФ: бесстрашный летчик-испытатель, он расширяет границы возможного и старательно избегает повышения в звании, которое заставило бы его приземлиться навсегда. Приступив к подготовке отряда выпускников «Топ Ган» для специальной миссии, Мэверик встречает лейтенанта Брэдли Брэдшоу — сына своего покойного друга, лейтенанта Ника Брэдшоу.

Впереди — неопределенность, за спиной — призраки прошлого. Мэверик вынужден противостоять своим глубинным страхам, которые грозят ожить в рамках миссии, требующей исключительной самоотверженности от тех, кто будет назначен на вылет.', 'Джозеф Косински', 2022, 'США', 'боевик,драма', 'https://www.kinopoisk.ru/film/572032/', 130, 8.3, 0.0, 'WATCHED', 1, '2023-02-04 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 575243, 'Пока мы молоды', 'Бездетная пара за 40 чувствует, что друзья, у которых появляются дети, от них отдаляются. В поисках нового круга общения они знакомятся с молодыми парнем и девушкой, с горящими глазами и целым вагоном безумных идей. На первый взгляд, у них нет совершенно ничего общего.  Но ведь никогда не поздно снова почувствовать себя молодым!

', 'Ноа Баумбак', 2014, 'США', 'драма,комедия', 'https://www.kinopoisk.ru/film/575243/', 97, 6.3, 0.0, 'WATCHED', 1, '2023-07-26 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 579484, 'Мой парень — ангел', 'XXI век. Мегаполис. Сотни, тысячи людей окружают тебя каждый день. Но ты даже и представить себе не можешь, что среди этой многоликой толпы прямо перед тобой может оказаться... Ангел.  Студентка Саша с большим трудом верит, что такое бывает. Ангелу Серафиму приходится приложить немало усилий, чтобы доказать ей, что Ангелы существуют. Но он не учёл одного – если девушка тебе поверит, она, скорее всего, тебя полюбит. А разве можно влюбиться в Ангела?', 'Вера Сторожева', 2011, 'Россия', 'фэнтези,мелодрама,комедия,приключения', 'https://www.kinopoisk.ru/film/579484/', 97, 6.6, 0.0, 'WATCHED', 1, '2021-12-08 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 580661, 'Пиноккио Гильермо дель Торо', 'История про деревянную куклу, которая превращается в настоящего мальчика.', 'Гильермо дель Торо,Марк Густафсон', 2022, 'США,Мексика,Франция', 'мультфильм,мюзикл,фэнтези,драма,семейный', 'https://www.kinopoisk.ru/film/580661/', 117, 7.6, 0.0, 'WATCHED', 1, '2023-02-26 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 589290, 'Бегущий по лезвию 2049', 'В недалеком будущем мир населен людьми и репликантами, созданными выполнять самую тяжелую работу. Работа офицера полиции Кей — держать репликантов под контролем в условиях нарастающего напряжения. Он случайно становится обладателем секретной информации, которая ставит под угрозу существование всего человечества. Желая найти ключ к разгадке, Кей решает разыскать Рика Декарда — бывшего офицера специального подразделения полиции Лос-Анджелеса, который бесследно исчез много лет назад.', 'Дени Вильнёв', 2017, 'США,Великобритания,Канада,Испания', 'фантастика,боевик,триллер,драма', 'https://www.kinopoisk.ru/film/589290/', 164, 8.0, 0.0, 'WATCHED', 1, '2022-04-20 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 591789, 'Философы: Урок выживания', 'В международной школе в Джакарте таинственный учитель философии в качестве выпускного экзамена предлагает 20 студентам провести эксперимент. Этот опыт будет самым экстремальным, с которым они когда-либо сталкивались. 

Используя только силу логики, студенты должны выбрать, кто из них будет достоин получить место в подземном бункере - единственном месте, где можно спастись от приближающейся ядерной катастрофы. Бункер рассчитан на десять человек, а значит, тех, кого не выбирают, ожидает жестокая смерть. Реальность классной комнаты эффектно перетекает в воображаемый, но в то же время пугающий мир надвигающегося апокалипсиса...', 'Джон Хаддлс', 2013, 'США,Индонезия', 'драма,фэнтези,история', 'https://www.kinopoisk.ru/film/591789/', 107, 5.6, 0.0, 'WATCHED', 1, '2022-08-03 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 607928, 'Преисподняя', 'История о девушке по имени Лиз, которая пытается сбежать от своего темного прошлого и скрывается от преследования «дьявольского» проповедника.', 'Мартин Колховен', 2016, 'Нидерланды,Франция,Германия,Бельгия,Швеция,Великобритания,США', 'триллер,драма,детектив,вестерн', 'https://www.kinopoisk.ru/film/607928/', 148, 7.0, 0.0, 'WATCHED', 1, '2023-10-04 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 647671, 'Охота', '42-летний Лукас живет в небольшой датской деревушке, работает воспитателем в детском саду и пытается оправиться после тяжелого развода. Жизнь постепенно налаживается: он встречает любимую женщину и восстанавливает отношения с сыном-подростком Маркусом. Но детская обида дочери его лучшего друга провоцирует случайную ложь, которая распространяется по небольшому сообществу, как вирус. Мир Лукаса трещит по швам, и он начинает борьбу за свои жизнь и честь.', 'Томас Винтерберг', 2012, 'Дания,Швеция', 'драма', 'https://www.kinopoisk.ru/film/647671/', 115, 8.3, 0.0, 'WATCHED', 1, '2022-10-26 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 687670, 'Превосходство', 'Выдающийся исследователь в области изучения искусственного интеллекта доктор Уилл Кастер работает над созданием компьютера, который сможет собрать в себе все знания и опыт, накопленные человечеством. Достаточно спорные эксперименты, проводимые Уиллом, прославили его и в то же время сделали основной целью радикальной анти-технологической группировки. Экстремисты делают всё возможное, чтобы остановить учёного.

Однако в своих попытках уничтожить Уилла они добиваются обратного и становятся невольными участниками становления его абсолютного превосходства. Для его жены Эвелин и лучшего друга Макса Вотерса, тоже учёных-исследователей, встаёт вопрос, должны ли они продолжать этот эксперимент. Их худшие опасения претворяются в жизнь, когда жажда знаний Уилла переходит в неконтролируемую жажду власти…', 'Уолли Пфистер', 2014, 'Великобритания,Китай,США', 'фантастика,драма,триллер', 'https://www.kinopoisk.ru/film/687670/', 119, 6.2, 0.0, 'WATCHED', 1, '2023-10-18 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 705356, 'Левиафан', 'Автослесарь Николай Сергеев живет со второй женой Лилей и сыном от первого брака в маленьком северном городке на берегу моря. Нечистый на руку мэр города Шелевят пытается изъять его дом и землю для собственных нужд. После двух проигранных судов Николай обращается за помощью к бывшему сослуживцу Дмитрию, успешному столичному адвокату. Но приезд московского гостя лишь усложняет и без того непростую жизнь Николая.', 'Андрей Звягинцев', 2014, 'Россия', 'драма,криминал', 'https://www.kinopoisk.ru/film/705356/', 141, 7.6, 0.0, 'WATCHED', 1, '2023-04-12 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 749503, 'По млечному пути', 'История о любви, происходящая в период боснийской войны.', 'Эмир Кустурица', 2016, 'Сербия,Великобритания,США,Аргентина,Мексика', 'фэнтези,драма,мелодрама,комедия,военный', 'https://www.kinopoisk.ru/film/749503/', 125, 6.3, 0.0, 'WATCHED', 1, '2023-05-04 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 757182, 'Белый Бог', 'Главная героиня после отъезда матери в Австралию осталась с отцом, а отец не рад ее собаке Хагену. К тому же, пес не поставлен на учет, и за ним начинает охоту санитарная инспекция. Сбежав от хозяйки, Хаген переживает серию передряг, а потом оказывается в собачьем приюте, где поднимает восстание против бесчеловечности тех, кто там работает.', 'Корнел Мундруцо', 2014, 'Венгрия,Германия,Швеция', 'триллер,драма', 'https://www.kinopoisk.ru/film/757182/', 121, 6.9, 0.0, 'WATCHED', 1, '2023-08-23 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 764739, 'Жена Чайковского', 'История ключевого эпизода биографии Петра Ильича Чайковского — его брака. Решение изменить свою жизнь, положить конец слухам и жениться стало причиной серьезного душевного кризиса.', 'Кирилл Серебренников', 2022, 'Россия,Франция,Швейцария', 'драма', 'https://www.kinopoisk.ru/film/764739/', 143, 6.5, 0.0, 'WATCHED', 1, '2023-07-05 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 775278, 'Энканто', 'Удивительная семья Мадригаль живет в спрятанном в горах Колумбии волшебном доме, расположенном в чудесном и очаровательном уголке под названием Энканто. Каждого ребёнка в семье Мадригаль магия этого места благословила уникальным даром — от суперсилы до способности исцелять. Увы, магия обошла стороной одну лишь юную Мирабель. Обнаружив, что магия Энканто находится в опасности, Мирабель решает, что именно она может быть последней надеждой на спасение своей особенной семьи.', 'Джаред Буш,Байрон Ховард,Чариз Кастро Смит', 2021, 'США', 'мультфильм,мюзикл,фэнтези,комедия,семейный', 'https://www.kinopoisk.ru/film/775278/', 102, 7.2, 0.0, 'WATCHED', 1, '2022-03-23 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 819846, 'Лобстер', 'В ближайшем будущем одиноких людей арестовывают и отправляют в специальный отель. Там они обязаны найти себе пару за 45 дней. Если им это не удается, то их превращают в животных и отпускают в лес.', 'Йоргос Лантимос', 2015, 'Ирландия,Великобритания,Греция,Франция,Нидерланды', 'драма,мелодрама,триллер,фантастика', 'https://www.kinopoisk.ru/film/819846/', 119, 7.1, 0.0, 'WATCHED', 1, '2023-05-10 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 821508, 'Мой король', 'Тони знакомится на вечеринке с Джорджио, и легкое увлечение перерастает в настоящую страсть. Десять лет всепоглощающей любви, полной безоглядного счастья и ослепляющей ревности. Оказавшись наедине с собой, Тони возвращается в мыслях к отношениям с Джоржио. Кто был этот человек? Кем она стала рядом с ним? Тони предстоит долгая работа, которая излечит душу и смягчит сердце.', 'Майвенн', 2015, 'Франция', 'драма,мелодрама', 'https://www.kinopoisk.ru/film/821508/', 124, 7.1, 0.0, 'WATCHED', 1, '2022-06-08 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 834394, 'В центре внимания', 'Основанная на реальных событиях история журналистского расследования одного из самых громких в истории США секс-скандалов. Корреспонденты бостонской газеты разоблачают случаи педофилии, в которых обвиняются представители римско-католической церкви.', 'Том Маккарти', 2015, 'США', 'драма,криминал,биография', 'https://www.kinopoisk.ru/film/834394/', 129, 8.1, 5.8, 'WATCHED', 1, '2024-01-09 19:46:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 839653, 'Вестсайдская история', 'Нью-Йорк, конец 1950-х. История противостояния двух уличных банд и невозможной любви юноши и девушки из враждующих группировок.', 'Стивен Спилберг', 2021, 'США', 'мюзикл,драма,мелодрама,криминал', 'https://www.kinopoisk.ru/film/839653/', 156, 7.2, 0.0, 'WATCHED', 1, '2022-03-09 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 840821, 'Кот в сапогах 2: Последнее желание', 'Промотав восемь жизней из девяти и до смерти испугавшись пришедшего за ним волка-охотника за головами, Кот в сапогах внимает совету врача и заселяется в дом местной кошатницы. Там он смиряется с установленными порядками, отращивает бороду и теряет тягу к подвигам и приключениям, но только до тех пор, пока не узнаёт о волшебной карте, которая указывает путь к где-то упавшей Звезде желаний. Кот в сапогах твёрдо решает отыскать Звезду, чтобы вернуть свои жизни, и в компании притворявшегося кошачьим пёсика отправляется красть карту у известного коллекционера волшебных предметов Джека Хорнера.', 'Джоэль Кроуфорд,Хануэль Меркадо', 2022, 'США,Япония', 'мультфильм,комедия,приключения,фэнтези', 'https://www.kinopoisk.ru/film/840821/', 102, 7.8, 0.0, 'WATCHED', 1, '2023-03-01 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 841897, 'Моди', 'Правдивая история невероятного романа между скупым рыботорговцем Эверетт и его экономкой Моди, чьи руки искалечила болезнь. Холостяк-затворник, покоренный ее силой и светом, помогает Моди раскрыться в творчестве и стать всенародно любимой художницей.', 'Эшлин Уолш', 2016, 'Канада,Ирландия', 'драма,мелодрама,биография', 'https://www.kinopoisk.ru/film/841897/', 115, 7.6, 0.0, 'WATCHED', 1, '2022-06-15 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 848894, 'Вторая жизнь Уве', 'Уве - пожилой въедливый ворчун, достающий соседей вечными придирками. Он впадает в ярость при виде брошенного не туда мусора или неправильно припаркованной машины. И кроет на чем свет стоит легкомысленную семейку новосёлов, в которой папаша и гвоздя вбить не способен. Зато Уве умеет всё. В доме и в гараже у него всегда идеальный порядок. Как и в мыслях. Вот только жизнь давно перестала иметь для него смысл.', 'Ханнес Холм', 2015, 'Швеция', 'драма,мелодрама,комедия', 'https://www.kinopoisk.ru/film/848894/', 116, 7.7, 0.0, 'WATCHED', 1, '2022-07-13 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 925669, 'Идеальные незнакомцы', 'Семеро закадычных друзей, собравшись за ужином, в шутку начинают игру - читать все смс вслух, а на звонки отвечать по громкой связи. Они и представить себе не могут, какие скелеты вылезут из их шкафов и какие удивительные открытия им предстоит сделать.', 'Паоло Дженовезе', 2015, 'Италия', 'драма,комедия', 'https://www.kinopoisk.ru/film/925669/', 96, 7.7, 0.0, 'WATCHED', 1, '2022-01-19 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 944098, 'Три билборда на границе Эббинга, Миссури', 'Спустя несколько месяцев после убийства дочери Милдред Хейс преступники так и не найдены. Отчаявшаяся женщина решается на смелый шаг - арендует на въезде в город три билборда и оставляет на них послание главе полиции Уильяму Уиллоуби. Когда в ситуацию оказывается втянут ещё и заместитель шерифа Диксон, инфантильный маменькин сынок со склонностью к насилию, борьба между Милдред и властями города только усугубляется.', 'Мартин Макдона', 2017, 'Великобритания,США', 'драма,криминал', 'https://www.kinopoisk.ru/film/944098/', 115, 8.1, 0.0, 'WATCHED', 1, '2022-06-22 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 958293, 'Леди Бёрд', 'Кристина МакФерсон учится в консервативной католической школе в Сакраменто. Она ищет себя, своё место в мире и пытается быть не похожей на других. Её волосы выкрашены в странный красно-розовый цвет, а имя Леди Бёрд она дала себе сама и именно так просит её называть. И главная её мечта - вырваться из этого провинциального захолустья и поехать учиться в Нью-Йорк.', 'Грета Гервиг', 2017, 'США', 'драма,комедия', 'https://www.kinopoisk.ru/film/958293/', 94, 7.4, 0.0, 'WATCHED', 1, '2023-08-09 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 958722, 'Твоё имя', 'Токийский парень Таки и провинциальная девушка Мицуха обнаруживают, что между ними существует странная связь. Во сне они меняются телами и проживают жизни друг друга. Но однажды эта способность исчезает так же внезапно, как появилась. Таки решает во что бы то ни стало отыскать Мицуху.', 'Макото Синкай', 2016, 'Япония', 'аниме,мультфильм,фэнтези,драма,мелодрама', 'https://www.kinopoisk.ru/film/958722/', 110, 8.4, 0.0, 'WATCHED', 1, '2022-11-30 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 965754, 'Дело храбрых', 'История о команде пожарных под названием Granite Mountain Hotshots, столкнувшихся в Аризоне с одним из самых смертоносных пожаров в истории.', 'Джозеф Косински', 2017, 'США', 'драма,триллер,биография,история', 'https://www.kinopoisk.ru/film/965754/', 134, 7.6, 0.0, 'WATCHED', 1, '2022-05-18 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 984309, 'Убийство священного оленя', 'Успешный кардиохирург Стивен живёт обычной размеренной семейной жизнью с женой Анной и двумя прелестными детьми. Но вскоре спокойствие нарушается призраком из прошлого Стивена, и у одного из его детей без видимой причины отказывают ноги.', 'Йоргос Лантимос', 2017, 'Ирландия,Великобритания', 'триллер,драма,фэнтези,детектив', 'https://www.kinopoisk.ru/film/984309/', 121, 7.0, 0.0, 'WATCHED', 1, '2023-05-10 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 1040827, 'Ночь воспоминаний', 'Вместе с родителями и обожаемым старшим братом Ю-соком 21-летний Чин-сок переезжает в новый дом. Прежний хозяин оставил свои вещи в одной комнате, и отец говорит сыновьям в неё не заходить, но Чин-сок постоянно слышит оттуда странные звуки. Парень готовится к экзаменам и принимает таблетки, поэтому семья считает, что это ему слышится. Однажды на глазах младшего брата Ю-сока похищают. Он возвращается через 19 дней, ничего не помнит о своём исчезновении и кажется брату слегка другим человеком.', 'Чан Хан-джун', 2017, 'Корея Южная', 'детектив,триллер,криминал', 'https://www.kinopoisk.ru/film/1040827/', 109, 7.4, 0.0, 'WATCHED', 1, '2022-06-29 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 1043758, 'Паразиты', 'Обычное корейское семейство Кимов жизнь не балует. Приходится жить в сыром грязном полуподвале, воровать интернет у соседей и перебиваться случайными подработками. Однажды друг сына семейства, уезжая на стажировку за границу, предлагает тому заменить его и поработать репетитором у старшеклассницы в богатой семье Пак. Подделав диплом о высшем образовании, парень отправляется в шикарный дизайнерский особняк и производит на хозяйку дома хорошее впечатление. Тут же ему в голову приходит необычный план по трудоустройству сестры.', 'Пон Джун-хо', 2019, 'Корея Южная', 'драма,триллер,комедия', 'https://www.kinopoisk.ru/film/1043758/', 131, 8.5, 0.0, 'WATCHED', 1, '2022-09-07 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 1044101, 'Теснота', '1998 год, Нальчик. Илана — девочка-подросток из хорошей семьи, которая всё делает наоборот. Перечит матери. Спорит с отцом. Чинит машины в автомастерской, не вылезая из спецодежды. Встречается с парнем, который не нравится её родителям. Пацанка и красавица, она идёт своим путём и жаждет свободы, но когда в доме происходит страшная трагедия, именно Илана оказывается единственной, кто способен спасти семью. Однако какой ценой?', 'Кантемир Балагов', 2017, 'Россия', 'драма', 'https://www.kinopoisk.ru/film/1044101/', 118, 6.8, 0.0, 'WATCHED', 1, '2023-03-29 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 1047626, 'Дождливый день в Нью-Йорке', 'Гэтсби — из состоятельной нью-йоркской семьи, его девушка Эшли — дочь банкира из Аризоны, оба учатся в колледже Ярдли. Когда местное издание отправляет Эшли в Нью-Йорк взять интервью у известного режиссера, Гэтсби приходит в восторг — теперь он покажет ей родной город. Парочка заселяется в шикарный номер с видом на Центральный парк и строит планы, но судьба распоряжается иначе: Эшли затягивает в мир звёздной богемы, а Гэтсби встречает бывших одноклассников и младшую сестру своей школьной любви.', 'Вуди Аллен', 2019, 'США', 'мелодрама,комедия', 'https://www.kinopoisk.ru/film/1047626/', 92, 6.5, 0.0, 'WATCHED', 1, '2023-09-27 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 1049453, 'АльфаГо', 'Могут ли компьютеры думать творчески, как люди? Возможно ли создать алгоритм, описывающий интуицию? Этими и другими вопросами задаются в компании Deep Mind, занимающейся искусственным интеллектом и недавно купленной Google. Ее создатель, вундеркинд Демис Хассабис, купил первый компьютер в 8 лет — на призовые от выигранного шахматного турнира. Его мечта — научить машину играть лучше человека — в арканоид, в Starcraft, в другие видеоигры, но особенно — в го, древнюю китайскую игру, которая считается самой сложной из когда-либо придуманных человеком. И вот программа создана — она называется AlphaGo — и уже обыграла профессионального игрока со счетом 5:0. Теперь у команды Хассабиса более серьезный вызов — сразиться с лидером мирового рейтинга, обладателем 9-го дана Ли Сэдолем.', 'Грег Кос', 2017, 'США', 'документальный,спорт', 'https://www.kinopoisk.ru/film/1049453/', 90, 7.8, 0.0, 'WATCHED', 1, '2022-04-13 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 1059224, 'Место встречи', 'Девять человек приходят в одно и то же место на встречу к таинственному Незнакомцу в надежде, что он исполнит их сокровенные желания. Загадочный мужчина может претворить в жизнь всё, что они захотят. Но за определенную цену... В обмен на осуществление мечты, каждому из гостей предлагается выполнить необычные задания. Чем сложнее исполнение этой мечты, тем выше цена. Каждый из героев должен сделать свой выбор — как далеко он готов зайти, чтобы получить желаемое. И так ли случайны судьбы посетителей этого места встречи?', 'Паоло Дженовезе', 2017, 'Италия', 'триллер,драма,детектив', 'https://www.kinopoisk.ru/film/1059224/', 105, 7.0, 0.0, 'WATCHED', 1, '2021-11-24 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 1077781, 'Убийцы цветочной луны', 'Вскоре после Первой мировой Эрнест Беркхарт, отслуживший во Франции поваром, приезжает искать удачи в Оклахому, где находится крупная резервация индейцев племени осейдж. В тех краях живет его дядя Уильям Хэйл, который носит прозвище Король — он землевладелец, скотопромышленник, друг индейцев и большой человек. Король убеждает Эрнеста посвататься к Молли Кайл, молодой женщине из зажиточной индейской семьи. Идея состоит в том, чтобы земельные права этой семьи со временем перешли к Беркхарту (читай к Хэйлу), а для этого всего лишь должны умереть мама Молли, её сёстры и она сама.', 'Мартин Скорсезе', 2023, 'США', 'триллер,драма,криминал,детектив,вестерн,история', 'https://www.kinopoisk.ru/film/1077781/', 206, 8.3, 0.0, 'WATCHED', 1, '2023-06-14 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 1103852, 'Укрась прощальное утро цветами обещания', 'Красавица Макия — из рода бессмертных. На протяжении веков многие армии пытались захватить её народ, чтобы завладеть секретом вечной жизни. И вот теперь, когда город разрушен, девушка прячется в лесу. Здесь она находит потерявшего родителей маленького мальчика Эриала и начинает о нём заботиться.', 'Мари Окада', 2018, 'Япония', 'аниме,мультфильм,драма,мелодрама,приключения,фэнтези', 'https://www.kinopoisk.ru/film/1103852/', 115, 7.4, 0.0, 'WATCHED', 1, '2022-11-16 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 1114967, 'Магазинные воришки', 'Небольшая семья бедного японского рабочего живет практически только на пенсию бабушки, поэтому некоторые из родственников иногда подворовывают в магазинах. Однажды, возвращаясь домой после очередной кражи, глава семейства утаскивает с балкона на первом этаже маленькую девочку, матери которой нет до неё никакого дела. Жена встречает находку нерадостно, но всё же принимает ребёнка. Скромное финансовое положение не мешает дружной семье жить счастливо, когда по телевизору они видят объявление о пропавшей девочке и решают не возвращать ребёнка законной матери.', 'Хирокадзу Корээда', 2018, 'Япония', 'драма', 'https://www.kinopoisk.ru/film/1114967/', 120, 7.9, 0.0, 'WATCHED', 1, '2022-09-28 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 1125892, 'Аллея кошмаров', '1939 год. Покончив со старой жизнью, Стэн Карлайл держит путь куда глаза глядят и прибивается к бродячему балагану. Там он начинает осваивать всевозможные способы развлечения и одурачивания публики, а особенно — «чтение» мыслей по методу одного из популярных в прошлом артистов. Вскоре Стэн решает выступать с подобным номером самостоятельно.', 'Гильермо дель Торо', 2021, 'США,Мексика,Канада', 'триллер,драма,криминал', 'https://www.kinopoisk.ru/film/1125892/', 150, 7.0, 0.0, 'WATCHED', 1, '2022-02-09 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 1134778, 'Платформа', 'Горен соглашается на участие в некоем эксперименте и вскоре приходит в себя в почти пустой комнате уровня 48, где имеются большие прямоугольные отверстия в полу и потолке. На каждом уровне находятся два человека, а сколько всего уровней — неизвестно. Этажи связывает общий колодец, по которому раз в день опускается платформа с едой, и чем ниже находятся люди, тем меньше у них шансов поесть. Каждый месяц происходит рокировка, и обитатели верхних уровней могут оказаться в самом низу, и наоборот. Поскольку разрешалось взять с собой один предмет, Горен выбрал томик «Дон Кихота», а его сосед прихватил большой самозатачивающийся нож.', 'Гальдер Гастелу-Уррутия', 2019, 'Испания', 'фантастика,триллер,драма', 'https://www.kinopoisk.ru/film/1134778/', 94, 7.0, 0.0, 'WATCHED', 1, '2023-01-18 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 1167711, 'Ради Лесли', 'Шесть лет назад мать-одиночка по имени Лесли выиграла в лотерею и с тех пор спускала все деньги на алкоголь и наркотики. Потратив последний цент, она возвращается домой в Западный Техас. Семья не особо рада её появлению, немногочисленные друзья отворачиваются. Лесли понимает, что может остаться на улице, и находит 20-летнего сына Джеймса. Чтобы заслужить второй шанс, ей нужно побороть свои пристрастия.', 'Майкл Моррис', 2022, 'США', 'драма', 'https://www.kinopoisk.ru/film/1167711/', 119, 7.1, 0.0, 'WATCHED', 1, '2023-02-26 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 1170018, 'Рождество на двоих', 'Кейт работает в магазине рождественских товаров, злоупотребляет выпивкой и давно бросила переживать из-за собственной жизни. Но всё меняется после знакомства с милым и очаровательным Томом.', 'Пол Фиг', 2019, 'Великобритания,США,Китай', 'фэнтези,драма,мелодрама,комедия', 'https://www.kinopoisk.ru/film/1170018/', 103, 6.5, 0.0, 'WATCHED', 1, '2021-12-22 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 1179041, 'Элвис', 'История жизни и творческого пути короля рок-н-ролла Элвиса Пресли через призму сложных взаимоотношений с его одиозным менеджером, полковником Томом Паркером. Они работали вместе более 20 лет: от начала карьеры Элвиса до его небывалой славы.', 'Баз Лурман', 2022, 'США,Австралия', 'биография,музыка,драма', 'https://www.kinopoisk.ru/film/1179041/', 159, 7.3, 0.0, 'WATCHED', 1, '2023-03-01 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 1221042, 'Дылда', 'История двух молодых женщин-фронтовичек, которые возвращаются в послевоенный Ленинград и пытаются обрести новую мирную жизнь, когда и вокруг, и главное, внутри них — руины.', 'Кантемир Балагов', 2019, 'Россия', 'драма,военный', 'https://www.kinopoisk.ru/film/1221042/', 130, 7.2, 0.0, 'WATCHED', 1, '2023-04-01 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 1262931, 'Власть пса', '1920-е годы. Братья Фил и Джордж владеют крупнейшим ранчо Монтаны. Несмотря на родство и совместный бизнес, у них мало общего: Фил груб, не любит мыться и не упускает возможность унизить слабых, а Джордж тих, вежлив и предпочитает спокойно вести бизнес. Когда Джордж женится на местной вдове Роуз, у которой есть сын-подросток, Фил никак не может с этим смириться.', 'Джейн Кэмпион', 2021, 'Новая Зеландия,Великобритания,Канада,Австралия', 'драма,вестерн', 'https://www.kinopoisk.ru/film/1262931/', 126, 6.8, 0.0, 'WATCHED', 1, '2022-02-02 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 1263423, 'Петровы в гриппе', 'Автослесарь Петров заболевает гриппом. С кашлем и температурой он едет в автобусе с работы домой, когда его настигает приятель Игорь и утаскивает с собой выпивать. В это время бывшую жену Петрова Нурлынису — сотрудницу библиотеки — на рабочем месте накрывают реалистичные видения. Жизнь семейства наполняется безумием, фантастикой и сюрреализмом.', 'Кирилл Серебренников', 2020, 'Россия,Франция,Швейцария,Германия', 'драма,фантастика', 'https://www.kinopoisk.ru/film/1263423/', 145, 6.7, 0.0, 'WATCHED', 1, '2023-07-12 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 1272469, 'Король Ричард', 'Комптон, 1988 год. Отец пяти дочерей Ричард Уильямс уже давно составил подробный план на будущее своих девочек и упорно ему следует, а из восьмилетней Винус и семилетней Серены он намеревается сделать звёзд тенниса. Хотя Ричард с женой Брэнди мало что понимают в подготовке профессиональных теннисистов, они сами тренировали дочек и как могли ставили им технику. Всемирно известный тренер Пол Коэн, который работает с Питом Сампрасом и Джоном Макинроем, соглашается на бесплатные уроки, но только для Винус. Тогда Ричард записывает занятия на камеру, и Брэнди на их основе начинает тренировать Серену.', 'Рейнальдо Маркус Грин', 2021, 'США', 'биография,спорт,драма', 'https://www.kinopoisk.ru/film/1272469/', 144, 7.5, 0.0, 'WATCHED', 1, '2022-02-23 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 1311466, 'CODA: Ребенок глухих родителей', 'Глостер, штат Массачусетс. Семья глухих ведет рыболовный бизнес. 17-летняя Руби — единственный слышащий член семьи — помогает глухим родителям и брату в рыбной ловле. В школе она присоединяется к местному хору, где понимает, что любит петь. Руководитель хора убеждает её подумать о музыкальной школе, и теперь девушка вынуждена выбирать между семьей и новой мечтой.', 'Шан Хейдер', 2020, 'Франция,Канада,США', 'драма,комедия,музыка', 'https://www.kinopoisk.ru/film/1311466/', 111, 8.0, 0.0, 'WATCHED', 1, '2022-02-16 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 1322324, 'Всё везде и сразу', 'В жизни Эвелин царит бардак. Она никак не может составить налоговый отчёт, пожилой отец постоянно требует внимания, муж витает в облаках, а ещё и дочка привела свою девушку знакомиться с семьёй. Во время визита в налоговую всё запутывается ещё сильнее — оказывается, Эвелин может скакать по параллельным вселенным и получать доступ к воспоминаниям и навыкам других версий самой себя. И теперь, в полнейшем хаосе, женщине придётся противостоять загадочной злой сущности, которая решила разрушить не только этот мир, но и всю мультивселенную.', 'Дэн Кван,Дэниэл Шайнерт', 2021, 'США', 'фантастика,комедия,боевик,приключения,драма', 'https://www.kinopoisk.ru/film/1322324/', 139, 7.8, 0.0, 'WATCHED', 1, '2022-05-25 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 1348487, 'Треугольник печали', 'Пара моделей Карл и Яя отправляются в роскошный круиз на яхте в компании богатых пассажиров, где можно встретить и русского бизнесмена, и британских производителей оружия, и гения IT. Капитан судна — марксист, находящийся в перманентном запое. Пока всё идёт своим чередом: гости отдыхают, персонал трудится, жена русского бизнесмена чудит. Но вскоре произойдёт неожиданное событие, которое перевернёт заведённый порядок и вынудит некоторых переосмыслить своё место и значимость.', 'Рубен Эстлунд', 2022, 'США,Швеция,Великобритания,Германия,Франция,Турция,Дания,Греция,Швейцария,Мексика', 'драма,комедия', 'https://www.kinopoisk.ru/film/1348487/', 147, 7.3, 0.0, 'WATCHED', 1, '2023-01-28 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 1354524, 'Банши Инишерина', '1923 год, островок Инишерин возле западного побережья Ирландии. Народу здесь мало, и компанию простоватому доброжелательному фермеру Подрику составляют рассудительная незамужняя сестра, недалекий сын полицейского, миниатюрная ослица Дженни и, главное, его лучший друг — пожилой скрипач Колм. Однажды Подрик, следуя ежедневным маршрутом, заходит за Колмом по дороге в паб, а тот вдруг отказывается не только выпивать, но даже разговаривать с ним. Прижатый к стенке Колм сообщает, что считает Подрика скучным, а если тот продолжит к нему приставать, он отрежет себе палец.', 'Мартин Макдона', 2022, 'Великобритания,США,Ирландия', 'драма,комедия', 'https://www.kinopoisk.ru/film/1354524/', 114, 7.7, 0.0, 'WATCHED', 1, '2023-02-19 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 1388683, 'Жена шпиона', '1940 год. Юсаку управляет торговой компанией в Кобе. Он женат на Сатоко. Находясь в командировке в Маньчжурии, Юсаку узнает страшную государственную тайну. Чтобы восстановить справедливость, он решает сообщить всему миру о своем открытии. Сатоко верит Юсаку, которого теперь обвиняют в предательстве, и клянется быть с ним независимо от последствий.', 'Киёси Куросава', 2020, 'Япония', 'драма,история,мелодрама', 'https://www.kinopoisk.ru/film/1388683/', 115, 6.6, 0.0, 'WATCHED', 1, '2022-09-21 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 1397888, 'Белфаст', 'Белфаст, 1960-е. Девятилетнему Бадди предстоит научиться взрослой жизни в мире, который внезапно изменился до неузнаваемости. Крепкое любящее сообщество и всё, к чему он привык, никогда не будут прежними. Неизменными остаются лишь радость, смех, музыка и созидательная магия кино.', 'Кеннет Брана', 2021, 'Великобритания', 'драма,биография', 'https://www.kinopoisk.ru/film/1397888/', 98, 7.3, 0.0, 'WATCHED', 1, '2022-03-02 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 1435399, 'Решение уйти', 'Детектив расследует смерть мужчины, упавшего со скалы. Вдова покойного сотрудничает со следствием, но чем дальше продвигается дело, тем больше детектив её подозревает и тем сильнее влюбляется.', 'Пак Чхан-ук', 2022, 'Корея Южная', 'детектив,триллер,мелодрама,криминал', 'https://www.kinopoisk.ru/film/1435399/', 138, 7.3, 0.0, 'WATCHED', 1, '2023-09-06 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 4308297, 'Говорят женщины', 'Женщины из общины меннонитов подвергаются многократным изнасилованиям, происходящим по ночам. Из-за отсутствия доказательств со стороны потерпевших эти инциденты объясняются нападением демонов или плодом фантазии. Во время отсутствия мужчин женщины собираются, чтобы решить, как действовать дальше.', 'Сара Полли', 2022, 'США', 'драма', 'https://www.kinopoisk.ru/film/4308297/', 104, 6.9, 0.0, 'WATCHED', 1, '2023-02-15 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 4321512, 'Кит', 'Страдающий ожирением мужчина по имени Чарли когда-то бросил семью ради любовника. Оказавшись на пороге смерти, он пытается восстановить отношения с дочерью-подростком Элли, которую не видел несколько лет.', 'Даррен Аронофски', 2022, 'США', 'драма', 'https://www.kinopoisk.ru/film/4321512/', 117, 7.7, 0.0, 'WATCHED', 1, '2023-03-08 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 4367437, 'Статистическая вероятность любви с первого взгляда', 'Хэдли и Оливер влюбляются друг в друга во время перелета из Нью-Йорка в Лондон. Вероятность того, что они когда-нибудь снова встретятся, кажется невозможной, но любовь и Лондон могут бросить вызов трудностям.', 'Ванесса Касвиль', 2023, 'Великобритания,США', 'драма,мелодрама', 'https://www.kinopoisk.ru/film/4367437/', 90, 6.9, 0.0, 'WATCHED', 1, '2023-10-25 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 4382259, 'Сядь за руль моей машины', 'Режиссёра Юсукэ приглашают поставить «Дядю Ваню» для театрального фестиваля в Хиросиме. По условиям договора он не может сам водить машину, поэтому ему предоставляют девушку-водителя — молчаливую Мисаки. Проводя вместе по несколько часов в день, Юсукэ начинает переосмыслять свои отношения с женой, с которой они жили, казалось, в счастливом браке до её внезапной смерти два года назад. А Мисаки пытается разобраться с собственным непростым прошлым.', 'Рюсукэ Хамагути', 2021, 'Япония', 'драма', 'https://www.kinopoisk.ru/film/4382259/', 179, 7.6, 0.0, 'WATCHED', 1, '2022-03-16 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 4395987, 'Город астероидов', '1955 год, небольшой вымышленный городок, расположенный возле кратера, оставшегося после падения астероида тысячи лет назад. Каждый год в этом месте проводится собрание юных астрономов, в котором участвуют ученики, их семьи, учителя, а также военные. Очередной такой слёт резко прерывается событиями, способными изменить мир.', 'Уэс Андерсон', 2023, 'США,Германия', 'фантастика,драма,мелодрама,комедия', 'https://www.kinopoisk.ru/film/4395987/', 105, 6.6, 0.0, 'WATCHED', 1, '2023-08-16 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 4412896, 'Белый шум', '1984 год, небольшой американский городок. Профессор Джек Глэдни, преподаватель в местном колледже и лучший специалист в стране по Адольфу Гитлеру, живёт с любимой женой Бабеттой и четырьмя детьми. Жизнь идёт своим чередом, старшие ребята живо интересуются всем происходящим в мире, увлечённый Элвисом коллега просит совета, как сделать лекции такими же увлекательными, а Джек замечает едва уловимые изменения в поведении жены. Привычному порядку приходит конец, когда в окрестностях происходит авария, в воздух поднимается облако ядовитого газа, и в городке объявляют срочную эвакуацию.', 'Ноа Баумбак', 2022, 'США,Великобритания', 'драма,комедия', 'https://www.kinopoisk.ru/film/4412896/', 136, 5.7, 0.0, 'WATCHED', 1, '2023-07-19 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 4472502, 'Фабельманы', 'Нью-Джерси, начало 1950-х. Впервые в жизни оказавшись в кинотеатре и увидев на экране крушение поезда, маленький Сэмми Фабельман был так впечатлён, что чуть не сломал дорогую игрушечную железную дорогу, когда пытался воспроизвести аварию. В терапевтических целях мама предлагает мальчику заснять игрушечную катастрофу на 8-миллиметровую камеру. Так детское хобби и съёмки дурашливых домашних сценок перерастают для Сэма в большую любовь и увлечение всей жизни — режиссуру кино.', 'Стивен Спилберг', 2022, 'США,Индия', 'драма', 'https://www.kinopoisk.ru/film/4472502/', 151, 7.5, 0.0, 'WATCHED', 1, '2023-02-01 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 4511218, 'Тар', 'Всемирно признанная дирижёр и композитор Лидия Тар становится первой в истории женщиной-дирижёром Берлинского филармонического оркестра. Она даёт интервью, выпускает книги, преподаёт и в новой должности приступает к репетициям симфонии № 5 Малера, а также заботится о своей партнёрше — первой скрипке оркестра — и маленькой приёмной дочери. Но когда одна из её бывших подопечных кончает с собой, безупречная репутация Лидии оказывается под угрозой.', 'Тодд Филд', 2022, 'США', 'драма,музыка', 'https://www.kinopoisk.ru/film/4511218/', 158, 7.4, 0.0, 'WATCHED', 1, '2023-02-11 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 4530539, 'Аттика', 'О крупнейшем тюремном бунте в истории США 1971 года в исправительном учреждении Аттики.', 'Трэйси Карри,Стэнли Нельсон', 2021, '', 'документальный', 'https://www.kinopoisk.ru/film/4530539/', 116, 7.5, 0.0, 'WATCHED', 1, '2022-03-23 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 4630822, 'Марсель, ракушка в ботинках', 'Марсель — морская ракушка в туфельках. Он живёт с бабушкой Конни и хочет найти свою семью, с которой вынужден был расстаться. О Марселе снимают документалку, и историю необычной ракушки узнаёт весь мир.', 'Дин Флейшер-Кэмп', 2021, 'США', 'мультфильм,фэнтези,драма,комедия,семейный', 'https://www.kinopoisk.ru/film/4630822/', 90, 7.7, 0.0, 'WATCHED', 1, '2023-03-01 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 4696197, 'Тихоня', 'Ирландия, 1981 год. Неблагополучная семья отправляет одну из своих дочерей на лето к дальним родственникам. Там девочка расцветает в любви и заботе, но в доме, где не должно быть никаких секретов, скрывается одна горькая правда.', 'Колм Барейд', 2021, 'Ирландия', 'драма', 'https://www.kinopoisk.ru/film/4696197/', 95, 7.7, 0.0, 'WATCHED', 1, '2023-03-11 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 4748316, 'Золотой инкассатор', 'История становления рэпера — от курдского беженца до циничного преступника и немецкой звезды.', 'Фатих Акин', 2022, 'Германия,Италия,Нидерланды', 'драма,криминал,биография,музыка', 'https://www.kinopoisk.ru/film/4748316/', 138, 6.8, 0.0, 'WATCHED', 1, '2023-04-19 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 4830353, 'Чудесная история Генри Шугара', 'История Генри Шугара, который способен видеть сквозь предметы и предсказывать будущее с помощью украденной им книги.', 'Уэс Андерсон', 2023, 'Великобритания,США', 'короткометражка,драма,комедия,приключения', 'https://www.kinopoisk.ru/film/4830353/', 37, 7.4, 0.0, 'WATCHED', 1, '2023-10-11 22:10:00', NULL, NULL);

INSERT INTO movies (created_at, updated_at, deleted_at, id, title, description, directors, year, countries, genres, link, duration, imdb_rating, rating, status, watch_count, finished_at, suggested_at, suggested_by)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 4831860, 'Вулкан любви', 'Катя Крафт и её муж Морис Поль Крафт — французские вулканологи, погибшие во время извержения вулкана Ундзэн на японском острове Кюсю. Известны как первопроходцы в съёмках, фотографировании и видеозаписи деятельности вулканов.', 'Сара Доса', 2022, 'США,Канада', 'документальный,биография', 'https://www.kinopoisk.ru/film/4831860/', 98, 7.6, 0.0, 'WATCHED', 1, '2023-03-01 22:10:00', NULL, NULL);

